services:
  backend-nodejs:
    image: node:18-alpine
    command: sh -c "npm install && npm start"
    ports:
      - 8080:8080
    working_dir: /app
    volumes:
      - ./:/app
    # environment:
    #   MYSQL_HOST: mysql
    #   MYSQL_USER: root
    #   MYSQL_PASSWORD: secret
    #   MYSQL_DB: todos
# docker compose up -d

